LIS/apps/Lib/urls.py
from django.urls import path
from . import views

app_name = 'readers'

urlpatterns = [
    path('', views.ItemListView.as_view(), name='list'),
    path('create/', views.ReaderCreateView.as_view(), name='create_reader'),
    path('update/<int:pk>', views.ReaderUpdateView.as_view(), name='update_reader'),
    path('read/<int:pk>', views.ReaderReadView.as_view(), name='read_reader'),
    path('delete/<int:pk>', views.ReaderDeleteView.as_view(), name='delete_reader')
]

LIS/apps/sora/app/urls.py
from django.conf.urls import url

from django.urls import path
from . import views

app_name = "sora"

urlpatterns = [
    path('', views.viewsOrder, name='order'),
    path('create/', views.orderCreate),
    path('received/', views.viewsResOrder, name='received'),
    path('<str:slug>/', views.orderDetail, name='detail'),
    path('<str:slug>/edit/', views.orderUpdate, name='update'),
    path('<str:slug>/delete/', views.orderDelete),
    # url(r'^posts/$', "<appname>.views.<function_name>"),
]

LIS/apps/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import login, logout
'''
urlpatterns = [
    path('accounts/login/', login),
    path('accounts/logout/', logout),
]
'''

LIS/urls.py
import patterns as patterns

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf.urls import handler404
from django.urls import path, re_path
from django.contrib.staticfiles import views
from rest_framework_jwt.views import obtain_jwt_token

from LIS.apps.accounts.views import *

from LIS.apps.sora.orderComments import *

app_name = "LIS"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('LIS.apps.blog.posts.urls', 'posts'), namespace='posts')),
    path('order/app/', include(("LIS.apps.sora.app.urls", 'order'), namespace='order')),
    path('readers/', include(("LIS.apps.Lib.urls", 'lib'), namespace='lib')),
    path('comments/', include(('LIS.apps.blog.comments.urls', 'comments'), namespace="comments")),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('api/auth/token/', obtain_jwt_token),
    path('api/users/', include(("LIS.apps.accounts.api.urls", 'users-api'), namespace='users-api')),
    path('api/comments/', include(("LIS.apps.blog.comments.api.urls", 'comments-api'), namespace='comments-api')),
    path('api/posts/', include(("LIS.apps.blog.posts.api.urls", 'posts-api'), namespace='posts-api')),
    # url(r'^posts/$', "<appname>.views.<function_name>"),
]


if settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', views.serve),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LIS/apps/accounts/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.

LIS/apps/Lib/forms.py
from django import forms

from pagedown.widgets import PagedownWidget
from .models import Readers
from django import forms
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin


class ReadersForms(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    rdr_id = forms.CharField(label='Читательский:')
    name = forms.CharField(label='ФИО:')

    class Meta:
        model = Readers
        fields = [
            "rdr_id",
            "name",
            "passport",
            "address",
            "email",
            "homephone",
            "workphone",
            "employment",
            "course",
            "profession",
        ]

LIS/apps/accounts/forms.py
from django import forms
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)

User = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField(label="Имя пользователя")
    password = forms.CharField(widget=forms.PasswordInput, label="Пароль")

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        # user_qs = User.objects.filter(username=username)
        # if user_qs.count() == 1:
        #     user = user_qs.first()
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("Невырно введены пользовательские данные.")
            if not user.check_password(password):
                raise forms.ValidationError("Неверный пароль.")
            if not user.is_active:
                raise forms.ValidationError("Данная учётная запись заблокирована.")
        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label='Введите е-мейл')
    email2 = forms.EmailField(label='Повторите е-мейл')
    password = forms.CharField(label='Ведите пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'email2',
            'password',
            'password2',
        ]

    def clean_email2(self):
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        if email != email2:
            raise forms.ValidationError("Несовпадает почта.")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("Введённая почта уже используется.")
        return email

    def clean_pass2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password != password2:
            raise forms.ValidationError("Пароли не совпадают.")
        return password

LIS/apps/blog/comments/forms.py
from django import forms


class CommentForm(forms.Form):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    content = forms.CharField(label='', widget=forms.Textarea)
    # parent_id = forms.IntegerField(widget=forms.HiddenInput, required=False)

LIS/apps/blog/posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]

LIS/apps/sora/app/forms.py
from django import forms

from pagedown.widgets import PagedownWidget
from .models import Order


class OrderForms(forms.ModelForm):

    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Order
        fields = [
            "title",  # Заголовок заявки
            "content",  # Текст сообщения
            "image",    # Изображение
            "depRec",   # Отдел получатель
            #"depSender", # Отдел отправитель
            "publish"  # Дата публикации
        ]

LIS/apps/sora/orderComments/forms.py
from django import forms


class OrderCommentForm(forms.Form):
    contentType = forms.CharField(widget=forms.HiddenInput)
    objectId = forms.IntegerField(widget=forms.HiddenInput)
    content = forms.CharField(label='', widget=forms.Textarea)

LIS/apps/Lib/views.py
# Create your views here.
from django.urls import reverse_lazy

from LIS.apps.Lib.forms import ReadersForms
from LIS.apps.Lib.models import Readers

from django.db.models import Q
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.http import Http404, JsonResponse
from django.contrib.messages.views import SuccessMessageMixin
from django.views import generic
from django.views.generic import ListView
from django.template.loader import render_to_string
from bootstrap_modal_forms.mixins import PassRequestMixin, DeleteAjaxMixin


class ItemListView(ListView):
    template_name = 'lib/readers_list.html'

    def get(self, request):
        if request.user.is_staff or request.user.is_superuser:
            queryset_list = Readers.objects.all()
        else:
            raise Http404

        query = request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                Q(rdr_id__icontains=query) |
                Q(name__icontains=query)
            ).distinct()

        return render(
            request=request,
            template_name=self.template_name,
            context=
            {
                "title": "[LIS]: Читатели",
                'object_list': get_paginated_page(request, queryset_list),
            })

    def post(self, request):
        if request.is_ajax():
            return JsonResponse({
                "result": True,
                "articles": render_to_string(
                    request=request,
                    template_name='list/readers_list.html',
                    context={'object_list': get_paginated_page(request, Readers.objects.all())}
                )
            })
        else:
            raise Http404()


def get_paginated_page(request, objects, number=10):
    current_page = Paginator(objects, number)
    page = request.GET.get('page') if request.method == 'GET' else request.POST.get('page')
    try:
        return current_page.page(page)
    except PageNotAnInteger:
        return current_page.page(1)
    except EmptyPage:
        return current_page.page(current_page.num_pages)


# Create
class ReaderCreateView(PassRequestMixin, SuccessMessageMixin, generic.CreateView):
    template_name = 'lib/modals/create_reader.html'
    form_class = ReadersForms
    success_message = 'Читатель успешно создан.'
    success_url = reverse_lazy('lib:list')


# Update
class ReaderUpdateView(PassRequestMixin, SuccessMessageMixin, generic.UpdateView):
    model = Readers
    template_name = 'lib/modals/update_reader.html'
    form_class = ReadersForms
    success_message = 'Данные читателя были успешно отредактированы и сохранены.'
    success_url = reverse_lazy('lib:list')


# Read
class ReaderReadView(generic.DetailView):
    model = Readers
    form_class = ReadersForms
    template_name = 'lib/modals/read_reader.html'


# Delete
class ReaderDeleteView(DeleteAjaxMixin, generic.DeleteView):
    model = Readers
    template_name = 'lib/modals/delete_reader.html'
    success_message = 'Читатель был удалён.'
    success_url = reverse_lazy('lib:list')


class ReadersListView(ListView):
    model = Readers
    template_name = 'lib/readers_list.html'


class ViewReadersForm:
    today = timezone.now().date()
    model = Readers

LIS/apps/accounts/api/views.py
from django.db.models import Q
from django.contrib.auth import get_user_model

from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST
from rest_framework.views import APIView

from rest_framework.filters import (
    SearchFilter,
    OrderingFilter,
)

from rest_framework.mixins import DestroyModelMixin, UpdateModelMixin
from rest_framework.generics import (
    CreateAPIView,
    DestroyAPIView,
    ListAPIView,
    UpdateAPIView,
    RetrieveAPIView,
    RetrieveUpdateAPIView
)
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,

)

from LIS.apps.blog.posts.api.permissions import IsOwnerOrReadOnly
from LIS.apps.blog.posts.api.pagination import PostLimitOffsetPagination, PostPageNumberPagination

User = get_user_model()

from .serializers import (
    UserCreateSerializer,
    UserLoginSerializer,
)


class UserCreateAPIView(CreateAPIView):
    serializer_class = UserCreateSerializer
    queryset = User.objects.all()
    permission_classes = [AllowAny]


class UserLoginAPIView(APIView):
    permission_classes = [AllowAny]
    serializer_class = UserLoginSerializer

    def post(self, request, *args, **kwargs):
        data = request.data
        serializer = UserLoginSerializer(data=data)
        if serializer.is_valid(raise_exception=True):
            new_data = serializer.data
            return Response(new_data, status=HTTP_200_OK)
        return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)

LIS/apps/accounts/personalArea/views.py
from django.conf import settings
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required


@login_required
def PersonalAreaViews(request):
    if not request.user.is_authenticated():
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

LIS/apps/accounts/views.py
import logging

from django.contrib.auth import (authenticate, get_user_model, login, logout)
from django.shortcuts import render, redirect
from .forms import UserLoginForm, UserRegisterForm

log = logging.getLogger(__name__)


def login_view(request):
    log.info('[acc.views.login_view]: Выполняется попытка авторизации...')
    print(request.user.is_authenticated)
    next = request.GET.get('next')
    title = "Авторизация пользователя"
    button = "Войти"
    log.info('[acc.views.login_view]: Выполняется функция GET...')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        log.info('[acc.views.login_view]: Выполняется сравнение введенных данных...')
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        if next:
            log.info('[acc.views.login_view]: ' + username + ' успешно авторизовался')
            return redirect(next)
        return redirect("/")
    context = {
        "form": form,
        "title": title,
        "button": button
    }
    return render(request, "accounts/form.html", context)


def register_view(request):
    log.info('[acc.views.register_view]: Выполняется попытка регистрации...')
    print(request.user.is_authenticated)
    next = request.GET.get('next')
    title = "Регистрация пользователя"
    button = "Принять"
    log.info('[acc.views.register_view]: Выполняется функция GET...')
    form = UserRegisterForm(request.POST or None)
    log.info('[acc.views.register_view]: Выполняется функция POST...')
    if form.is_valid():
        log.info('[acc.views.register_view]: Выполняется проверка на корректность ввода...')
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        if next:
            return redirect(next)
        return redirect("/")

    context = {
        "form": form,
        "title": title,
        "button": button
    }
    return render(request, "accounts/form.html", context)


def logout_view(request):
    log.info('[acc.views.logout_view]: Выполняется выход из под учётной записи...')
    logout(request)
    log.info('[acc.views.logout_view]: Выход произведён успешно.')
    return redirect("/")


''''
# Регистрация пользователя
def register(request):
    form = UserCreationForm()

    if request.method == 'POST':
        data = request.POST.copy()
        errors = form.get_validation_errors(data)
        if not errors:
            new_user = form.save(data)
            return HttpResponseRedirect("/books/")
    else:
        data, errors = {}, {}

    return render_to_response("accounts/register.html", {
        'form' : forms.FormWrapper(form, data, errors)
    })

# Авторизация пользователя
def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = auth.authenticate(username=username, password=password)
    if user is not None and user.is_active:
        # Правильный пароль и пользователь "активен"
        auth.login(request, user)
        # Перенаправление на "правильную" страницу
        return HttpResponseRedirect("/accounts/loggedin/")
    else:
        # Отображение страницы с ошибкой
        return HttpResponseRedirect("/accounts/invalid/")

# Выйти из под авторизованного пользователя
def logout(request):
    auth.logout(request)
    # Перенаправление на страницу.
    return HttpResponseRedirect("/accounts/loggedout/")
'''''

LIS/apps/additionalFunctions/errorCodes/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

'''
def handler400(request):
    response = render_to_response('errors/400.html', {}, context_instance=RequestContext(request))
    response.status_code = 400
    return response


def handler403(request):
    response = render_to_response('errors/403.html', {}, context_instance=RequestContext(request))
    response.status_code = 403
    return response


def handler404(request):
    response = render_to_response('errors/404.html', {}, context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('errors/500.html', {}, context_instance=RequestContext(request))
    response.status_code = 500
    return response
'''

LIS/templates/lib/edit_form_success.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel"> {{ Readers.id }}</h4>
              </div>
              <div class="modal-body">
                  <p>Fuck yeah!</p>
                  <script>
                    setTimeout(function() { jQuery('#modal').modal('hide'); }, 1000);
                    $('body').on('hidden.bs.modal', '.modal', function () {
                        $(this).removeData('bs.modal');
                    });
                  </script>
              </div>
              <div class="modal-footer">
              </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

LIS/templates/lib/modalAddReaders.html
{% load crispy_forms_tags %}

{% block head_extra %}
    {{ form.media }}

{% endblock head_extra %}

{% block modal %}
    <div class='col-sm-6'>

        <form method='POST' action='' enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form|crispy }}
            <input type='submit' class='btn btn-default' value='Добавить читателя'/>
        </form>
    </div>
{% endblock modal %}

LIS/templates/lib/modalReaders.html
{% load i18n widget_tweaks %}
<div class="modal fade" id="modalReader" tabindex="-1" role="dialog" aria-labelledby="ModalInfoReadrs"
     aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form id="item_update_form" method='post' class="form" role="form" action='{% url 'lib:detail' readers.pk %}'>
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="myModalLabel">Item {{ object_list.pk }}</h4>
                </div>

                <div class="modal-body">
                    Карта читателя - {{ object_list.rdr_id }}<br>
                    ФИО: {{ object_list.name }}<br>
                    Номер читательского: {{ object_list.rdr_id }}<br>
                    Пол: {{ object_list.sex }}<br>
                    Статус читателя: {{ object_list.code }}<br>
                    День рождения: {{ object_list.birthday }}<br>
                    Паспрорт: {{ object_list.passport }}<br>
                    Адрес: {{ object_list.address }}<br>
                    Рабочий телефон: {{ object_list.workphone }}<br>
                    Домашний телефон: {{ object_list.homephone }}<br>
                    Электронная почта: {{ object_list.email }}<br>
                    Пейджер: {{ object_list.pager }}<br>
                    Место работы/учёбы: {{ object_list.employment }}<br>
                    Курс: {{ object_list.course }}<br>
                    Профессия: {{ object_list.profession }}<br>
                    Занимаемая должность: {{ object_list.post }}<br>
                    Дата регистрации: {{ regdate }}<br>
                    абонимент: {{ reregdate }}<br>
                    Примечание: {{ instance.notes }}<br>
                    Сиглы: {{ instance.siglas }}<br>
                    Читальный зал: {{ sigl1 }}<br>
                    Зал периодики: {{ sigl2 }}<br>
                    ИКО: {{ sigl3 }}<br>
                    Интерактивный зал: {{ sigl4 }}

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-primary">Сохранить изменения</button>
                </div>
            </form>
        <script>
            var form_options = { target: '#modal', success: function(response) {} };
            $('#item_update_form').ajaxForm(form_options);
        </script>
        </div>
    </div>
</div>

LIS/templates/lib/readersDetail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
    {{ instance.title }} | {{ block.super }}
{% endblock head_title %}


{% block post_detail_link %}
    <li><a href='{{ instance.getAbsoluteUrl }}'>{{ instance.title }}</a></li>
{% endblock %}



{% block content %}
    <div class='col-sm-6 col-sm-offset-3'>
        {% if instance.image %}
            <img src='{{ instance.image.url }}' class='img-responsive'/>
        {% endif %}
        <h1>{{ name }}
            <small>
                {% if instance.draft %}<span style='color:red;'>Draft</span> {% endif %}{{ instance.publish }}
            </small>
        </h1>

        <!-- {% if instance.read_time|time:"i" <= "01" %} < 1 minute {% else %}{{ instance.read_time|time:"i" }}
             minutes {% endif %} -->


        <p>Время прочтения: {% if instance.readTime <= 1 %} < 1 Минуты {% else %}{{ instance.readTime }}
            минут(ы) {% endif %}</p>
        {% if instance.user.get_full_name %}
            <p>Отправитель: {{ instance.user.get_full_name }}</p>
            <p>Отдел отправитель: {{ instance.user.groups.get }}</p>
            <p>Проверочное поле: {{ instance.depRec }}</p>
        {% endif %}

            <hr/>
    </div>
        <div class='row'>
            <div class='col-sm-12 '>
                <div class='post-detail-item'>{{ instance.getMarkdown }}</div>
                <hr/>

                <br/>
            </div>
        </div>

{% endblock content %}

LIS/templates/lib/readers_list.html
{% extends "base.html" %}

{% block extra_js %}
    <script src="http://malsup.github.com/jquery.form.js"></script>
{% endblock %}

{% block content %}

    <!-- Шапка -->
    <h1>{{ title }}</h1>
    {% load widget_tweaks %}
        <!-- <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        </div> /.modal -->

        <form method='GET' action='' class='row'>
            <div class='col-sm-10 '>
                <div class='input-group mb-3'>
                    <input class='form-control' type='text' name='q' placeholder='Поиск читателя'
                           value='{{ request.GET.q }}'/>
                    <span class='input-group-append'>
                    <!-- <input class='btn btn-default' type='submit' value='Search' /> -->
                    <button class='btn btn-outline-secondary' type='submit'>Поиск <i class="fa fa-search"></i></button>
                </span>
                </div>
            </div>
        </form>
    <!-- Таблица вывода читателей -->

    <div class="row">
        <div class="modal-body">
            <table class="table">
                <thead>
                <tr>
                    <th>№</th>
                    <th>Читательский</th>
                    <th>ФИО</th>
                    <th>Категория читателя</th>
                    <th>Просмотр/Редакт/Удаление</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in object_list %}
                    <tr>
                        <td>{{ obj.id }}</td>
                        <td><a href="{% url 'lib:read_reader' obj.pk %}" class="read-reader" data-toggle="modal">{{ obj.rdr_id }}</a></td>
                        <td>{{ obj.name }}</td>
                        <td><span class="price">{{ obj.code }}</span></td>
                        <td>
                            <button type="button" class="read-reader btn btn-sm btn-primary" data-id="{% url 'lib:read_reader' obj.pk %}" title="Профиль читателя"><span class="fa fa-address-card-o"></span></button>
                            <button type="button" class="read-reader btn btn-sm btn-primary" data-id="{% url 'lib:read_reader' obj.pk %}" title="Списк книг на руках"><span class="fa fa-book"></span></button>
                            <button type="button" class="update-reader btn btn-sm btn-success" data-id="{% url 'lib:update_reader' obj.pk %}" title="Редактировать читателя"><span class="fa fa-pencil"></span></button>
                            <button type="button" class="delete-reader btn btn-sm btn-danger" data-id="{% url 'lib:delete_reader' obj.pk %}" title="Удалить читателя"><span class="fa fa-trash"></span></button>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        <!--
            {{ obj.get_markdown|truncatechars_html:120 }}
            <hr class="bg-primary">
            <a href="{{ obj.get_absolute_url }}" class="btn btn-outline-primary" role="button">Просмотр</a>-->
        </div>
    </div>

<div class="btn-group justify-content-center" role="group" aria-label="Basic example">
  <button type="button" class="create-reader btn btn-secondary"><span class="fa fa-plus mr-2"></span>Добавить читателя</button>
  <button type="button" class="btn btn-secondary">Спсиок книг на руках</button>
  <button type="button" class="btn btn-secondary">Сортировка</button>
</div>
{% block extrascripts %}
  <script type="text/javascript">
    $(function () {

      // Add reader button
      $(".create-reader").modalForm({formURL: "{% url 'lib:create_reader' %}"});

      // Update reader buttons
      $(".update-reader").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      });

      // Read reader buttons
      $(".read-reader").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      });

      // Delete reader buttons
      $(".delete-reader").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      });

    });
  </script>
{% endblock extrascripts %}



    <!-- Пагинация -->


    <br><br>
        <div class="pagination justify-content-center">
        {% load bootstrap_pagination from bootstrap4 %}
        {% for article in object_list %}

        {% endfor %}
        {% bootstrap_pagination object_list pages_to_show="5" %}
    </div>
    <!--
    <div class="pagination justify-content-center">
        <nav aria-label="...">
          <ul class="pagination justify-content-center">
          {% if object_list.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" tabindex="-1">&laquo; Туда</a>
            </li>
              {% else %}
                  <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1">&laquo; Туда</a>
            </li>
          {% endif %}
            <li class="page-item disabled">
              <a class="page-link" href="#">Страница {{ object_list.number }} из {{ object_list.paginator.num_pages }}<span class="sr-only">(current)</span></a>
            </li>
            {% if object_list.has_next %}
              <li class="page-item">
              <a class="page-link" href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Сюда &raquo;</a>
            </li>
              {% else %}
                  <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1">Сюда &raquo;</a>
            </li>
          {% endif %}
          </ul>
        </nav>-->
    </div>


{% endblock content %}

LIS/templates/lib/tempDetails.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block content %}
            <h3>Карта читателя - {{ instance.rdr_id }}</h3>
            <p>ФИО: {{ instance.name }}
            <p>Номер читательского: {{ instance.rdr_id }}</p>
            <p>Пол: {{ instance.sex }}</p>
            <p>Статус читателя: {{ instance.code }}</p>
            <p>День рождения: {{ birthday }}</p>
            <p>Паспрорт: {{ instance.passport }}</p>
            <p>Адрес: {{ instance.address }}</p>
            <p>Рабочий телефон: {{ instance.workphone }}</p>
            <p>Домашний телефон{{ instance.homephone }}</p>
            <p>Электронная почта: {{ instance.email }}</p>
            <p>Пейджер: {{ instance.pager }}</p>
            <p>Место работы/учёбы: {{ instance.employment }}</p>
            <p>Курс: {{ instance.course }}</p>
            <p>Профессия: {{ instance.profession }}</p>
            <p>Занимаемая должность: {{ instance.post }}</p>
            <p>Дата регистрации: {{ regdate }}</p>
            <p>абонимент: {{ reregdate }}</p>
            <p>Примечание: {{ instance.notes }}</p>
            <p>Сиглы: {{ instance.siglas }}</p>
            <p>Читальный зал: {{ sigl1 }}</p>
            <p>Зал периодики: {{ sigl2 }}</p>
            <p>ИКО: {{ sigl3 }}</p>
            <p>Интерактивный зал: {{ sigl4 }}</p>


        <button type="button" class="btn btn-success">Обновить дату</button>
        <button type="button" class="btn btn-primary">Редактировать</button>
        <button type="button" class="btn btn-danger">Удалить</button>

{% endblock content %}