LIS/apps/Lib/urls.py
from django.urls import path
from . import views

app_name = 'readers'

urlpatterns = [
    path('', views.ItemListView.as_view(), name='list'),
    path('create/', views.ReaderCreateView.as_view(), name='create_reader'),
    path('update/<int:pk>', views.ReaderUpdateView.as_view(), name='update_reader'),
    path('read/<int:pk>', views.ReaderReadView.as_view(), name='read_reader'),
    path('delete/<int:pk>', views.ReaderDeleteView.as_view(), name='delete_reader')
]

LIS/apps/sora/app/urls.py
from django.conf.urls import url

from django.urls import path
from . import views

app_name = "sora"

urlpatterns = [
    path('', views.viewsOrder, name='order'),
    path('create/', views.orderCreate),
    path('received/', views.viewsResOrder, name='received'),
    path('<str:slug>/', views.orderDetail, name='detail'),
    path('<str:slug>/edit/', views.orderUpdate, name='update'),
    path('<str:slug>/delete/', views.orderDelete),
    # url(r'^posts/$', "<appname>.views.<function_name>"),
]

LIS/apps/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import login, logout
'''
urlpatterns = [
    path('accounts/login/', login),
    path('accounts/logout/', logout),
]
'''

LIS/urls.py
import patterns as patterns

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf.urls import handler404
from django.urls import path, re_path
from django.contrib.staticfiles import views
from rest_framework_jwt.views import obtain_jwt_token

from LIS.apps.accounts.views import *

from LIS.apps.sora.orderComments import *

app_name = "LIS"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('LIS.apps.blog.posts.urls', 'posts'), namespace='posts')),
    path('order/app/', include(("LIS.apps.sora.app.urls", 'order'), namespace='order')),
    path('readers/', include(("LIS.apps.Lib.urls", 'lib'), namespace='lib')),
    path('comments/', include(('LIS.apps.blog.comments.urls', 'comments'), namespace="comments")),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('api/auth/token/', obtain_jwt_token),
    path('api/users/', include(("LIS.apps.accounts.api.urls", 'users-api'), namespace='users-api')),
    path('api/comments/', include(("LIS.apps.blog.comments.api.urls", 'comments-api'), namespace='comments-api')),
    path('api/posts/', include(("LIS.apps.blog.posts.api.urls", 'posts-api'), namespace='posts-api')),
    # url(r'^posts/$', "<appname>.views.<function_name>"),
]


if settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', views.serve),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LIS/apps/accounts/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.

LIS/apps/blog/comments/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.db import models


class CommentManager(models.Manager):
    def all(self):
        qs = super(CommentManager, self).filter(parent=None)
        return qs

    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type=content_type, object_id=obj_id).filter(parent=None)
        return qs

    def create_by_model_type(self, model_type, slug, content, user, parent_obj=None):
        model_qs = ContentType.objects.filter(model=model_type)
        if model_qs.exists():
            SomeModel = model_qs.first().model_class()
            obj_qs = SomeModel.objects.filter(slug=slug)
            if obj_qs.exists() and obj_qs.count() == 1:
                instance = self.model()
                instance.content = content
                instance.user = user
                instance.content_type = model_qs.first()
                instance.object_id = obj_qs.first().id
                if parent_obj:
                    instance.parent = parent_obj
                instance.save()
                return instance
        return None


class Comment(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        default=1,
    )
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE)

    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CommentManager()

    class Meta:
        ordering = ['-timestamp']

    def __unicode__(self):
        return str(self.user.username)

    def __str__(self):
        return str(self.user.username)

    def get_absolute_url(self):
        return reverse("comments:thread", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("comments:delete", kwargs={"id": self.id})

    def children(self):  # replies
        return Comment.objects.filter(parent=self)

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

LIS/apps/blog/posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
#from django.utils.text import slugify
from pytils.translit import slugify
from markdown_deux import markdown
# from comments.models import Comment # Модуль коментов
from LIS.apps.blog.comments.models import *
from .utils import get_read_time


# Create your models here.
# MVC MODEL VIEW CONTROLLER


# Post.objects.all()
# Post.objects.create(user=user, title="Some time")

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    # filebase, extension = filename.split(".")
    # return "%s/%s.%s" %(instance.id, instance.id, extension)
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" % (new_id, filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              width_field="width_field",
                              height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time = models.IntegerField(default=0)  # models.TimeField(null=True, blank=True) #assume minutes
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    def get_api_url(self):
        return reverse("posts-api:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var


pre_save.connect(pre_save_post_receiver, sender=Post)

LIS/apps/Lib/forms.py
from django import forms

from pagedown.widgets import PagedownWidget
from .models import Readers
from django import forms
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin


class ReadersForms(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    rdr_id = forms.CharField(label='Читательский:')
    name = forms.CharField(label='ФИО:')

    class Meta:
        model = Readers
        fields = [
            "rdr_id",
            "name",
            "passport",
            "address",
            "email",
            "homephone",
            "workphone",
            "employment",
            "course",
            "profession",
        ]

LIS/apps/blog/comments/forms.py
from django import forms


class CommentForm(forms.Form):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    content = forms.CharField(label='', widget=forms.Textarea)
    # parent_id = forms.IntegerField(widget=forms.HiddenInput, required=False)

LIS/apps/blog/posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]

LIS/apps/sora/orderComments/forms.py
from django import forms


class OrderCommentForm(forms.Form):
    contentType = forms.CharField(widget=forms.HiddenInput)
    objectId = forms.IntegerField(widget=forms.HiddenInput)
    content = forms.CharField(label='', widget=forms.Textarea)

LIS/apps/Lib/views.py
# Create your views here.
from django.urls import reverse_lazy

from LIS.apps.Lib.forms import ReadersForms
from LIS.apps.Lib.models import Readers

from django.db.models import Q
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.http import Http404, JsonResponse
from django.contrib.messages.views import SuccessMessageMixin
from django.views import generic
from django.views.generic import ListView
from django.template.loader import render_to_string
from bootstrap_modal_forms.mixins import PassRequestMixin, DeleteAjaxMixin


class ItemListView(ListView):
    template_name = 'lib/readers_list.html'

    def get(self, request):
        if request.user.is_staff or request.user.is_superuser:
            queryset_list = Readers.objects.all()
        else:
            raise Http404

        query = request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                Q(rdr_id__icontains=query) |
                Q(name__icontains=query)
            ).distinct()

        return render(
            request=request,
            template_name=self.template_name,
            context=
            {
                "title": "[LIS]: Читатели",
                'object_list': get_paginated_page(request, queryset_list),
            })

    def post(self, request):
        if request.is_ajax():
            return JsonResponse({
                "result": True,
                "articles": render_to_string(
                    request=request,
                    template_name='list/readers_list.html',
                    context={'object_list': get_paginated_page(request, Readers.objects.all())}
                )
            })
        else:
            raise Http404()


def get_paginated_page(request, objects, number=10):
    current_page = Paginator(objects, number)
    page = request.GET.get('page') if request.method == 'GET' else request.POST.get('page')
    try:
        return current_page.page(page)
    except PageNotAnInteger:
        return current_page.page(1)
    except EmptyPage:
        return current_page.page(current_page.num_pages)


# Create
class ReaderCreateView(PassRequestMixin, SuccessMessageMixin, generic.CreateView):
    template_name = 'lib/modals/create_reader.html'
    form_class = ReadersForms
    success_message = 'Читатель успешно создан.'
    success_url = reverse_lazy('lib:list')


# Update
class ReaderUpdateView(PassRequestMixin, SuccessMessageMixin, generic.UpdateView):
    model = Readers
    template_name = 'lib/modals/update_reader.html'
    form_class = ReadersForms
    success_message = 'Данные читателя были успешно отредактированы и сохранены.'
    success_url = reverse_lazy('lib:list')


# Read
class ReaderReadView(generic.DetailView):
    model = Readers
    form_class = ReadersForms
    template_name = 'lib/modals/read_reader.html'


# Delete
class ReaderDeleteView(DeleteAjaxMixin, generic.DeleteView):
    model = Readers
    template_name = 'lib/modals/delete_reader.html'
    success_message = 'Читатель был удалён.'
    success_url = reverse_lazy('lib:list')


class ReadersListView(ListView):
    model = Readers
    template_name = 'lib/readers_list.html'


class ViewReadersForm:
    today = timezone.now().date()
    model = Readers

LIS/apps/accounts/api/views.py
from django.db.models import Q
from django.contrib.auth import get_user_model

from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST
from rest_framework.views import APIView

from rest_framework.filters import (
    SearchFilter,
    OrderingFilter,
)

from rest_framework.mixins import DestroyModelMixin, UpdateModelMixin
from rest_framework.generics import (
    CreateAPIView,
    DestroyAPIView,
    ListAPIView,
    UpdateAPIView,
    RetrieveAPIView,
    RetrieveUpdateAPIView
)
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,

)

from LIS.apps.blog.posts.api.permissions import IsOwnerOrReadOnly
from LIS.apps.blog.posts.api.pagination import PostLimitOffsetPagination, PostPageNumberPagination

User = get_user_model()

from .serializers import (
    UserCreateSerializer,
    UserLoginSerializer,
)


class UserCreateAPIView(CreateAPIView):
    serializer_class = UserCreateSerializer
    queryset = User.objects.all()
    permission_classes = [AllowAny]


class UserLoginAPIView(APIView):
    permission_classes = [AllowAny]
    serializer_class = UserLoginSerializer

    def post(self, request, *args, **kwargs):
        data = request.data
        serializer = UserLoginSerializer(data=data)
        if serializer.is_valid(raise_exception=True):
            new_data = serializer.data
            return Response(new_data, status=HTTP_200_OK)
        return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)

LIS/apps/accounts/personalArea/views.py
from django.conf import settings
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required


@login_required
def PersonalAreaViews(request):
    if not request.user.is_authenticated():
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

LIS/apps/additionalFunctions/errorCodes/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

'''
def handler400(request):
    response = render_to_response('errors/400.html', {}, context_instance=RequestContext(request))
    response.status_code = 400
    return response


def handler403(request):
    response = render_to_response('errors/403.html', {}, context_instance=RequestContext(request))
    response.status_code = 403
    return response


def handler404(request):
    response = render_to_response('errors/404.html', {}, context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('errors/500.html', {}, context_instance=RequestContext(request))
    response.status_code = 500
    return response
'''

LIS/templates/_footer.html
<div class="panel-footer text-center py-3 bg-light">© 2018 Copyright:<br>
    <a>The project was developed by the </a><a href="https://gitlab.com/Alpaca-soft"> Alpaca-Soft </a>group.<br>
    This project is licensed under the <a href="https://gitlab.com/Alpaca-soft/LIS/blob/master/LICENSE">Apache License
        2.0</a>.
</div>

LIS/templates/_header.html
{% load static %}

  <!-- Messages -->
  <div>
    {% if messages %}
      {% for message in messages %}
        <div style="border-radius:0;" {% if message.tags %} class="alert alert-icon alert-{{ message.tags }} alert-dismissible fade show mb-0" role="alert" {% endif %}>
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    {% endif %}
  </div>
  <!-- End Messages -->

<!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
            <a class="navbar-brand" href="{% url "posts:list" %}">Главное</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="navbar-brand" href="{% url "sora:order" %}">СПЗ<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">

                        <a class="navbar-brand " href="{% url "lib:list" %}">Читатели</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="navbar-brand dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Дополнительно
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="/admin/">Модераторская</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    <!--
                    <li class="nav-item">
                        <a class="navbar-brand" href="#">[Временно]</a>
                    </li>-->
                </ul>
                <form class="form-inline my-2 my-lg-0">

                    {% if not request.user.is_authenticated %}
                        <a class="navbar-brand" href='{% url "register" %}'><span class="fa fa-user-plus"></span> Регистрация</a>
                        <a class="navbar-brand" href='{% url "login" %}'><span class="fa fa-user-secret"></span> Авторизация</a>
                    {% else %}
                        <a class="navbar-brand" href='{% url "logout" %}'>Выход</a>
                        <a class="navbar-brand dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="fa fa-user-o"></span>
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <label>Вы авторизованы как:</label>
                            <label>{{ user.get_full_name }} </label>
                            <label>{{ user.groups.get }}</label>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Профиль пользователя</a>
                        </div>
                    {% endif %}
                </form>
            </div>
        </nav>
<!-- End Navbar -->

LIS/templates/_modal.html
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

LIS/templates/base.html
{% load staticfiles %}
<!--DOCTYPE html -->
<html>
    <head>
        <meta charset=utf-8>
        <title>{% block head_title %}LIS{% endblock head_title %}</title>
        <!-- Latest compiled and minified CSS -->

        <link rel='stylesheet' href='{% static "css/base.css" %}'/>
        <link rel='stylesheet' href='{% static "js/index.js" %}'/>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <style>
            {% block style %}{% endblock style %}
        </style>

        {% block head_extra %} {% endblock head_extra %}
        <style>
            body {
                background-image: url("{% static "images/bg.jpg" %}"); /* Путь к фоновому изображению */
                background-attachment: fixed; /* Фиксируем фон веб-страницы */
            }
        </style>
    </head>
    <body>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}">

        <div id="fb-root"></div>

        {% include "messages_display.html" %}

        {% include "_header.html" %}
        <!--
{% block javascript_footer %}
    <script src="/static/js/index.js"></script>
{% endblock %}


        <div class='container'>
            <ol class='breadcrumb'>
                <li><a href='{% url "posts:list" %}'>Главная</a></li>
                {% block post_detail_link %}
                {% endblock %}
            </ol>
        </div>-->
        <!-- Контент -->
        <div class="container bg-light col-lg-7">

            <div class='col-sm'>
                {% block content %}{% endblock content %}
            </div>


        </div>
        <!-- Футер -->
            {% include "_footer.html" %}
            {% include "_modal.html" %}

            <!-- JavaScript -->
        {% block scripts %}
          <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
          <script src="{% static 'js/popper.min.js' %}"></script>
          <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
          <!-- You can alternatively load the minified version -->
          <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
        {% endblock scripts %}

        {% block extrascripts %}{% endblock extrascripts %}

        <script type="text/javascript">
            $(document).ready(function () {
                $(".content-markdown").each(function () {
                    var content = $(this).text()
                    var markedContent = marked(content)
                    $(this).html(markedContent)
                })
                $(".post-detail-item img").each(function () {
                    $(this).addClass("img-responsive");
                })

                var contentInput = $("#id_content");

                function setContent(value) {
                    var markedContent = marked(value)
                    $("#preview-content").html(markedContent)
                    $("#preview-content img").each(function () {
                        $(this).addClass("img-responsive")
                    })
                }

                setContent(contentInput.val())
                contentInput.keyup(function () {
                    var newContent = $(this).val()
                    setContent(newContent)
                })
                var titleInput = $("#id_title");

                function setTitle(value) {
                    $("#preview-title").text(value)
                }

                setTitle(titleInput.val())
                titleInput.keyup(function () {
                    var newContent = $(this).val()
                    setTitle(newContent)
                })
                $(".comment-reply-btn").click(function (event) {
                    event.preventDefault();
                    $(this).parent().next(".comment-reply").fadeToggle();
                })
                // preview-title
                // preview-content
            })
        </script>

    </body>
</html>

LIS/templates/messages_display.html
<!--{% if messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">

        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {% if "html_safe" in message.tags %}
                        {{ message|safe }}
                    {% else %}{{ message }}
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
    </div>

{% endif %}-->